org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.configuration-cache=false

minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

mod_version=3.8.0-clean
maven_group=hsn.modod

fabric_api_version=0.155.2+26.2
cloth_config_version=26.2.155
modmenu_version=20.0.1
