#!/usr/bin/env python3
"""HSNL compiler — lowers .hsnl data-parallel kernels to C.

The generated C is what `make hsnl` compiles into libhsn_hsnl.so.
Missing Python or a parse error is fail-open: the Fabric jar still runs.
"""
from __future__ import annotations

import argparse
import pathlib
import re
import sys

C_TYPES = {
    "f32": "float",
    "f64": "double",
    "u8": "uint8_t",
    "i32": "int32_t",
}


def strip_comments(src: str) -> str:
    out = []
    for line in src.splitlines():
        if "#" in line:
            line = line[: line.index("#")]
        out.append(line)
    return "\n".join(out)


def parse_kernels(src: str) -> list[dict]:
    src = strip_comments(src)
    kernels = []
    pattern = re.compile(
        r"kernel\s+(\w+)\s*\((.*?)\)\s*\{(.*?)\}\s*",
        re.S,
    )
    for match in pattern.finditer(src):
        name, args_raw, body = match.group(1), match.group(2), match.group(3)
        args = []
        for part in [p.strip() for p in args_raw.split(",") if p.strip()]:
            bits = part.split()
            if len(bits) != 3 or bits[0] not in {"in", "out", "imm"}:
                raise SystemExit(f"bad arg `{part}` in kernel {name}")
            kind, typ, ident = bits
            if typ not in C_TYPES:
                raise SystemExit(f"bad type `{typ}` in kernel {name}")
            args.append((kind, typ, ident))
        body = " ".join(body.split())
        if not body.startswith("foreach i in n:"):
            raise SystemExit(f"kernel {name} must start with `foreach i in n:`")
        assign = body[len("foreach i in n:") :].strip()
        lhs, _, rhs = assign.partition("=")
        lhs = lhs.strip()
        rhs = rhs.strip()
        if not lhs.endswith("[i]"):
            raise SystemExit(f"kernel {name} destination must be NAME[i]")
        dest = lhs[:-3]
        kernels.append({"name": name, "args": args, "dest": dest, "rhs": rhs})
    if not kernels:
        raise SystemExit("no kernels parsed")
    return kernels


def c_expr(expr: str, args: list[tuple[str, str, str]]) -> str:
    """Translate a tiny expression subset to C, using pointer[i] for arrays."""
    names = {ident: kind for kind, _typ, ident in args}

    def rewrite_ident(match: re.Match[str]) -> str:
        token = match.group(0)
        if token in {"rsqrt", "i", "n"}:
            return token
        kind = names.get(token)
        if kind in {"in", "out"}:
            return f"{token}[i]"
        return token

    text = re.sub(r"\b[A-Za-z_]\w*\b", rewrite_ident, expr)
    # HSNL `name[i]` already rewrites to name[i][i] if we also match after.
    text = text.replace("[i][i]", "[i]")
    text = re.sub(r"\brsqrt\s*\(", "hsnl_rsqrt(", text)
    # boolean compare used as u8 assignment
    if any(op in expr for op in (">", "<", "<=", ">=", "==")) and "?" not in expr:
        text = f"(uint8_t)(({text}) ? 1u : 0u)"
    return text


def emit_c(kernels: list[dict]) -> str:
    lines = [
        "/* Generated by hsnlc.py — do not hand-edit. */",
        "#include <stdint.h>",
        "#include <math.h>",
        "",
        "static inline float hsnl_rsqrt(float x) {",
        "    if (!(x > 0.f)) return 0.f;",
        "    float y = 1.f / sqrtf(x);",
        "    return y * (1.5f - 0.5f * x * y * y);",
        "}",
        "",
        "static inline double hsnl_rsqrt_d(double x) {",
        "    if (!(x > 0.0)) return 0.0;",
        "    double y = 1.0 / sqrt(x);",
        "    return y * (1.5 - 0.5 * x * y * y);",
        "}",
        "",
    ]
    for k in kernels:
        cname = "hsn_hsnl_" + k["name"]
        params = []
        null_checks = []
        for kind, typ, ident in k["args"]:
            ctype = C_TYPES[typ]
            if kind == "imm":
                params.append(f"{ctype} {ident}")
            elif kind == "in":
                params.append(f"const {ctype}* {ident}")
                null_checks.append(ident)
            else:
                params.append(f"{ctype}* {ident}")
                null_checks.append(ident)
        params.append("uint64_t n")
        lines.append("/* generated from kernel %s */" % k["name"])
        lines.append("__attribute__((visibility(\"default\")))")
        lines.append(f"void {cname}({', '.join(params)}) {{")
        cond = " || ".join(f"!{n}" for n in null_checks)
        lines.append(f"    if (({cond}) || n == 0) return;")
        rhs = c_expr(k["rhs"], k["args"])
        dest = k["dest"]
        rhs1 = rhs.replace("[i]", "[i + 1]")
        rhs2 = rhs.replace("[i]", "[i + 2]")
        rhs3 = rhs.replace("[i]", "[i + 3]")
        rhs4 = rhs.replace("[i]", "[i + 4]")
        rhs5 = rhs.replace("[i]", "[i + 5]")
        rhs6 = rhs.replace("[i]", "[i + 6]")
        rhs7 = rhs.replace("[i]", "[i + 7]")
        lines.append("    uint64_t i = 0;")
        lines.append("    for (; i + 8 <= n; i += 8) {")
        lines.append(f"        {dest}[i] = {rhs};")
        lines.append(f"        {dest}[i + 1] = {rhs1};")
        lines.append(f"        {dest}[i + 2] = {rhs2};")
        lines.append(f"        {dest}[i + 3] = {rhs3};")
        lines.append(f"        {dest}[i + 4] = {rhs4};")
        lines.append(f"        {dest}[i + 5] = {rhs5};")
        lines.append(f"        {dest}[i + 6] = {rhs6};")
        lines.append(f"        {dest}[i + 7] = {rhs7};")
        lines.append("    }")
        lines.append("    for (; i + 4 <= n; i += 4) {")
        lines.append(f"        {dest}[i] = {rhs};")
        lines.append(f"        {dest}[i + 1] = {rhs1};")
        lines.append(f"        {dest}[i + 2] = {rhs2};")
        lines.append(f"        {dest}[i + 3] = {rhs3};")
        lines.append("    }")
        lines.append("    for (; i < n; ++i) {")
        lines.append(f"        {dest}[i] = {rhs};")
        lines.append("    }")
        lines.append("}")
        lines.append("")
    lines.append("__attribute__((visibility(\"default\")))")
    lines.append("int hsn_hsnl_abi(void) { return 0x48534E4C; } /* HSNL */")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Compile HSNL to C")
    parser.add_argument("source", type=pathlib.Path)
    parser.add_argument("-o", "--output", type=pathlib.Path, required=True)
    args = parser.parse_args()
    src = args.source.read_text(encoding="utf-8")
    kernels = parse_kernels(src)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(emit_c(kernels), encoding="utf-8")
    print(f"hsnlc: {len(kernels)} kernels -> {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
